### ISSUE TITLE
Consider advertising compatibility with older Stash releases

### ISSUE THREAD

**Issue by Gribnif** [pragbits/stash2slack#14]
We're currently using Stash 3.5.x (yes, my license has expired and I'm too cheap/lazy to upgrade), and I wanted to report that this plugin works fine with it. However, the plugin manager reports it as "incompatible".

Would you please consider changing the minimum required version down to 3.5? Thanks.

**Comment by pragbits** [comment]
schedule for 1.5

**Comment by pragbits** [comment]
implemented in 1.5
