### ISSUE TITLE
Add global configuration for notifications

### ISSUE THREAD

**Issue by mathieumg** [pragbits/stash2slack#15]
Would it be possible to have global settings for notification types? (Just like the webhook URL and the channel list currently have) That way, if a single repository doesn't override the notification types, it uses the global ones.

We have a lot of repositories and configuring every single one individually is tedious, and we only want the same type of notifications for all of them, which used to be the default behavior. 

Thanks in advance!

**Comment by pragbits** [comment]
implemented in 1.6

**Comment by mathieumg** [comment]
Awesome, thank you! :)

**Comment by wiredmax** [comment]
Cool!
