### ISSUE TITLE
Pull Request message is very talky

### ISSUE THREAD

**Issue by telcus** [pragbits/stash2slack#16]
At the moment when an action on a pull request is pushed to Slack each message takes roughly 13 lines of text. We only really care about the person who initiated the action, the action and the link to the pull request.

It would handy if the following output from pull requests had toggles for turning on or off:
Description
Users/Reviewers
Source and Destination

Alternatively we'd be happy with a compact mode for pull requests that looked similar to
**Joe Bloggs**
opened a pull request *link to pull request*

**Comment by pragbits** [comment]
implemented in 1.6
