### ISSUE TITLE
Disable stash2slack on forks (global setting)

### ISSUE THREAD

**Issue by marco-roy** [pragbits/stash2slack#17]
Hey guys,

First of all, thank you so much for this plugin, it's awesome & does exactly what we need!

However, we do have one small issue with it. It's not super critical priority since there is a workaround, but it would be very, very nice to have a simpler solution:

 1. We currently have slack notifications enabled by default on all our repos (both pushes & PRs).
 2. However, this leads us to see all the pushes that devs do on their own forks. We don't want to see that (I can't imagine why anyone would). Especially since devs don't have access to each other's forks.
 3. The current workaround is to ask each developer to override the global/default settings *on each of their current & future forks*, in order to disable notifications from them. Or to not use the global/default settings, and instead enable notifications manually for each repo (which we have *many* of).
 
As you can imagine, this is far from a perfect solution. The best solution I can think of would be a global setting to enable/disable notifications on forks completely, or at least to automatically override the default settings on forks, with no notifications by default.

Let me know what you think!

**Comment by sdegabriele** [comment]
+1

**Comment by pragbits** [comment]
Alright, scheduling this to v1.7 (Sorry we are a bit busy now, but will do when we have a chance. Thanks for the ticket and for your patience - Daniel / Pragbits)

**Comment by pragbits** [comment]
implemented in 1.7.0

**Comment by marco-roy** [comment]
This is working great, thanks guys!
