### ISSUE TITLE
Include branch name (and commit counts?) on Minimal push notifications

### ISSUE THREAD

**Issue by bloveridge** [pragbits/stash2slack#19]
# Problem

We use a lot of feature branches and do a lot of rebases in our workflow, and we like to have Stash notifications come into our general development room alongside our regular dev chatter. Unfortunately, we haven't been able to find a good middle ground with the current options for Push notifications.

1. **Verbose**—yeah, we expected this one to be verbose, and it sure is! When doing a rebase, this also brought over comments on the various commits that suddenly were in the new branch history. Way too noisy, so moved down to Compact.
2. **Compact**—had really high hopes for this one. During regular development this is great, because it shows the author, branch, SHA1, and summary.
    * During a rebase, however, this also gets really noisy. It adds a line for each and every commit that was added on the branch being rebased atop. If your branch is dozens (or, heaven forbid, hundreds) of commits behind then this quickly spams your slack room and is painful.
    * So we decided to try Minimal.
3. **Minimal**—unfortunately, this is just too minimal to be useful to us. All it shows is "Push on [repo] by [author]." There is no differentiation between whether it was pushed to master or a feature branch, and it isn't useful for us to find out "hey, somebody just pushed something somewhere."

# Proposal

Change **Minimal** to be just a tiny bit less minimal, displaying at the very least the branch that was pushed to, and ideally the number of commits.

#### Example: current behavior
Stash: Push on `insight` by `Ben Loveridge <email>`. See commit list.
Stash: Push on `insight` by `Ben Loveridge <email>`. See commit list.

#### Example: after
Stash: Push on `insight : master` by `Ben Loveridge <email>`. See commit list.
Stash: Push on `insight : feature/the_new_thing` by `Ben Loveridge <email>`. See commit list.

#### Example: after (alternate)
Stash: Push on `insight : master` by `Ben Loveridge <email>` (1 commit). See commit list.
Stash: Push on `insight : feature/the_new_thing` by `Ben Loveridge <email>` (3 commits). See commit list.

**Comment by bloveridge** [comment]
All in all, thanks very much for your plugin, we are putting it to good use, and it is nice that it supports PR operations that the official Stash -> HipChat integration supports (specifically PR approval).

**Comment by marco-roy** [comment]
+1

**Comment by marco-roy** [comment]
Looks like the "alternate" example has been implemented in 1.7. Great work guys!

Push on `SuchRepo` branch `master` by `Very Quality <very@quality.com>` (1 commit). See [commit list]().
