### ISSUE TITLE
It'd be cool to have option to send notifications about push to master, and not any push

### ISSUE THREAD

**Issue by AlexeyDmitriev** [pragbits/stash2slack#24]

**Comment by pragbits** [comment]
Hi, could you please explain this a bit more? A flag that enables pushing only to master, and disable all other branches?

**Comment by AlexeyDmitriev** [comment]
Yeah I mean option(flag) so that when it's turned on, notifications about pushes to master are sent to slack, but not about pushes to other branches.

May be, it makes sense to add text field for comma-separated list of branches instead.

**Comment by lucymhdavies** [comment]
I like the sound of this.

Comma separated list of branches would work, but I'm thinking a list of regexes would work better.

e.g. for my use case, I care about any branches named "master" or "release/.*"

**Comment by ivho** [comment]
Yeah, this would be really sweet, a list of channels each accompanied by a regex for branch names would be my ideal scenario.

**Comment by pragbits** [comment]
implemented in 2.0.3

**Comment by pragbits** [comment]
You can do now the following (in the channel name section)
 * Leave it empty (in this case the message will be simply posted to the default channel specified in the web hook)
 * Use a single value as the channel name (this overrides the channel name configured in the webbook)
 * NEW FEATURE: You can add a comma separated list of pairs (pattern, channel) eg: bugfix/.*->#test-bf,master->#test-master 

For the last option, the format must be:
PATTERN->CHANNELNAME,ANOTHERPATTERN->ANOTHERCHANNELNAME

example: 
 bugfix/.*->#test-bf,master->#test-master

**Comment by pragbits** [comment]
released on Xmas: http://blog.pragbits.com/it/2015/12/24/stash2slack-release-204/
