### ISSUE TITLE
v1.7.0 Unable to connect to SSL Service due to PKIX Path

### ISSUE THREAD

**Issue by nabsource** [pragbits/stash2slack#27]
Related Link:

https://confluence.atlassian.com/display/KB/Unable+to+Connect+to+SSL+Services+due+to+PKIX+Path+Building+Failed

Example Error Output
-2015-11-03 16:45:10,162 ERROR [AtlassianEvent::thread-2] user @2KDDHDZx2114x1068170x0 8srzly 192.0.0.1,127.0.0.1 "POST /projects/path/repos/name/pull-requests HTTP/1.1" c.pragbits.stash.tools.SlackNotifier #error during http request execution in SlackNotifier: 
-javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

javac -version:
javac 1.7.0_25

stash version: 
v3.5.0

**Comment by nabsource** [comment]
javac -version

javac 1.7.0_25

**Comment by pragbits** [comment]
I really don't get this. Usually this happens when slack.com has issues with certificates, but I don't see that holds.

Even tried to use the SSLPoke test app:
bash-3.2$ java SSLPoke hooks.slack.com 443
Successfully connected

All seems just OK.
