### ISSUE TITLE
stash2slack 2.0.0 fails with bibutcket server 4.0.2

### ISSUE THREAD

**Issue by rcdeoliveira** [pragbits/stash2slack#28]
Hello,

I have a fresh installation of bitbucket server 4.0.2 with stash2slack 2.0.0 running on Windows. I could not get notifications in Slack, when I see atlassian-bitbucket.log I have the next error: "error during httpPost in SlackNotifier: invalid_payload"
I think that is a bug. Anyone has solution for these? 

Thanks in advance.

**Comment by pragbits** [comment]
Hi. I've tried to reproduce your issue, so I installed 4.0.2 on a windows host, using stash2slack 2.0.0 from marketplace, but it is just all working for me fine.

Could you provide more information? Server logs, etc?

**Comment by rcdeoliveira** [comment]
I was reading server logs and every event for SlackNotifier said something like:

IP "POST /scm/vto/web-app.git/git-receive-pack HTTP/1.1" c.p.b.tools.SlackNotifier #error during httpPost in SlackNotifier: invalid_payload

**Comment by dmonti** [comment]
Same error here...

Log:
`#error during httpPost in SlackNotifier: invalid_payload`

`    payload string: {"channel":"#ci","mrkdwn":true,"link_names":true,"attachments":[{"mrkdwn_in":["pretext","text","title","fields","fallback"],"fields":[{"title":"Reviewers","value":"@lamancio @lflopes @damedeiros @dasilva ","short":false},{"title":"Source","value":"_SA — legado_\n`AP-11081`","short":true},{"title":"Destination","value":"_SA — legado_\n`develop`","short":true}],"fallback":"Kennedy Correia de Assuncao opened pull request \"Refatoração da query do relatório 1040 para incluir a nova cobrança Isentado\". \u003chttp://portal:7990/projects/SA/repos/legado/pull-requests/60/overview|(open)\u003e","color":"#2267c4","text":"opened pull request \u003chttp://portal:7990/projects/SA/repos/legado/pull-requests/60/overview|#60: Refatoração da query do relatório 1040 para incluir a nova cobrança Isentado\u003e","author_name":"Kennedy Correia de Assuncao","author_icon":"https://secure.gravatar.com/avatar/c5556c8f1ff2c53b2c5bc22b692ca9c4.jpg?s\u003d16\u0026d\u003dmm"}],"username":"bitbucket","icon_url":"https://a.slack-edge.com/12b5a/plugins/bitbucket/assets/service_48.png","icon_emoji":":large_red_circle:"}
`

**Comment by PhilJay** [comment]
I am getting the same error with Bitbucket Server v4.13.0

Could this be related to the fact that my server is configured to be reachable via **HTTPS** only?

`SlackNotifier #error during httpPost in SlackNotifier: invalid_payload`
`SlackNotifier payload string: {"text":"Push on https://bitbucket.mydomain.com/..." ...}`
