### ISSUE TITLE
If a new branch is pushed the entire history gets posted to slack

### ISSUE THREAD

**Issue by JamesIry** [pragbits/stash2slack#3]
1) Pick an existing stash project with several existing commits. 
2) Configure stash2slack
3) Create a new branch. 
4) Create one new commit on the new branch.
5) Push the branch to stash.

Expected: The single new commit is sent to Slack
Actual: The entire history of the project is sent to Slack

**Comment by pragbits** [comment]
Thanks, will check that!

**Comment by pragbits** [comment]
Okay, if the fromHash in the ref change is zero (0000000000000000000000000000000000000000), then this probably means this is a new branch. In this case, I only emit the latest commit to the slack message. As a consequence, if you create a new branch and commit to it more than once before pushing, you will only get the latest commit displayed in the slack message (you can always click on the `see commit list` link though).

**Comment by JamesIry** [comment]
Thanks! Very fast fix and it works fine.
