### ISSUE TITLE
Slack plugin stopped working suddenly

### ISSUE THREAD

**Issue by norbertpy** [pragbits/stash2slack#34]
We have a few repositories on Stash and we set up the WebHook to get activities notification on Slack. It was working flawlessly until a week, or so, ago. The strange thing is, it still works for one repo but doesn't work for others. I updated the WebHook but it didn't work.

How do you debug to see what's wrong?

**Comment by pragbits** [comment]
Hello. Look for the string "SlackNotifier" in the bitbucket server log to see anything unusual (error). Interesting that it works for one repo, but not for the rest of them. No one reported this so far...

**Comment by pragbits** [comment]
If you don't see "#error during httpPost in SlackNotifier" or "#error during http request execution in SlackNotifier" in your bitbucket server log, this means that the plugin sends the HTTP request to slack server for sure, and the trouble is at slack side.

**Comment by norbertpy** [comment]
Sure. Thanks for the tip. I'll report back.

**Comment by pragbits** [comment]
Make sure you're using at least v2.0.1 (that is where I've added the logging)

**Comment by pragbits** [comment]
any news on this, @norbertpy? Note that the latest release has null pointer exception bug when deserialising settings, but it is unrelated to your issue.

**Comment by norbertpy** [comment]
@pragbits, unfortunately I don't have access to the server to dig in but as far as I could get it seems like we're using and older version of this. Our stash is not updated yet. But as I said, the interesting point is it still works for one repo but not the others. 

Thanks for following up though. I'll close this down until I get further information.
