### ISSUE TITLE
2.0.4+ Channel name setting

### ISSUE THREAD

**Issue by tadamo** [pragbits/stash2slack#39]
It seems as of version 2.0.4, the 'Channel name' setting is no longer working. It doesn't work from the global or repo settings. My notifications all go to the default Slack channel setup in my Incoming Webhook integration. I've tried 2.0.5 & 2.0.4 with no success. Downgrading to version 2.0.0 got this working for me again. We're currently running Atlassian Bitbucket v4.0.1.

**Comment by hornste** [comment]
Also have this issue. 

running v2.0.5 and BitBucket Server 4.3.2

**Comment by dszabo** [comment]
fixed! Sorry for the delay!
