### ISSUE TITLE
Branch delete is not informative

### ISSUE THREAD

**Issue by JamesIry** [pragbits/stash2slack#4]
1) Select a stash project with several branches.
2) Configure stash2slack
3) Delete from stash (e.g. git push origin --delete [somebranch])

Expected: an indication that "somebranch" was deleted
Actual: "Push on [repo name] by [author]. See commit list" with no indication of branch delete.

**Comment by pragbits** [comment]
if the branch is deleted via `git push origin --delete [branchname]` then the following message is generated: `{refname} deleted by {username} <{email_address}>.`

**Comment by pragbits** [comment]
note that if you delete a branch via the stash web interface no slack message is generated because no push has happened (plugin only subscribed for push and pullreq events)

**Comment by JamesIry** [comment]
Thanks. Very fast fix!
