### ISSUE TITLE
Despite setting a specific channel in the repository settings, notifications are sent to the main slack channel.

### ISSUE THREAD

**Issue by ArekSredzki** [pragbits/stash2slack#40]
We are using the 2.0.5 version with Bitbucket Server v4.3.2

**Comment by ArekSredzki** [comment]
@dszabo thank you! However, I think you made a mistake in decrementing the release version :)

I appreciate the promo response, can't wait to get this working :D

**Comment by dszabo** [comment]
yes, sorry. I will push a correct version soon.

**Comment by ArekSredzki** [comment]
Thanks!
