### ISSUE TITLE
Duplicate messages sent on Bitbucket Server 4.7.1

### ISSUE THREAD

**Issue by ArekSredzki** [pragbits/stash2slack#49]
Upon upgrading to Bitbucket Server 4.7.1 all messages have duplicates (show up twice in chat). Making a very compelling argument to disable this add-on :(

**Comment by visch** [comment]
Can confirm this happens on 4.8.1

**Comment by johannesmpt** [comment]
same problem here

**Comment by tk8817** [comment]
same problem here, anyone working on this?

**Comment by bcreasy** [comment]
@tk8817, see discussion on PR #52. Specifically the comment on July 27th from @rrobert42.
