### ISSUE TITLE
"Needs work" notification is empty

### ISSUE THREAD

**Issue by ffittschen** [pragbits/stash2slack#50]
Hi!
We use Bitbucket Server 4.4.1 and if I mark the pull request with the "Needs work" flag, stash2slack sends an empty message to our slack channel. 

Is there any way to fix this?

<img width="231" alt="screen shot 2016-06-21 at 09 57 20" src="https://cloud.githubusercontent.com/assets/7734806/16222124/cc442884-3796-11e6-93dc-2bcb5bd980b4.png">

**Comment by OndraM** [comment]
Same here. Moreover there is no way how to disable this notification, when pull request notifications are enabled. Unchecking all fields in "Filter pull request events based on activity types" won't make any difference :-(.
